import React, { useState } from 'react';
import { Calendar, MapPin, FileText, Scale, ChevronDown, ChevronUp, ExternalLink } from 'lucide-react';

const CourtCaseTimeline = () => {
  const [expandedCases, setExpandedCases] = useState(new Set());
  const [selectedStatus, setSelectedStatus] = useState('all');

  const cases = [
    {"id":1,"date":"2025-09-01","defendant":"Jonathan Michael Alfaro","location":"Los Angeles","address":"n/a","charge":"Assault on federal officer using a deadly or dangerous weapon","chargeType":"felony","description":"Defendant allegedly used his car as a weapon against two Federal Protective Service agents.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Accepted plea deal for a misdemeanor count; sentencing scheduled for July 9, 2026","source":"https://www.documentcloud.org/documents/26185383-usa-v-alfaro-e791cd17-18f8-4b93-9563-09d63e9b7123/"},
    {"id":2,"date":"2025-09-04","defendant":"Joseph Blandon-Saavedra","location":"San Bernardino, California","address":"n/a","charge":"Assaulting, resisting or impeding a federal officer using a dangerous or deadly weapon","chargeType":"felony","description":"ICE and HSI tried to pull over the defendant, who was the target of an immigration enforcement operation. Defendant allegedly back his vehicle into an agent's vehicle, then pulled forward into another agent's vehicle. An agent broke the defendant's window open and took him into custody. Appeal pending on one of the counts.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Case is on hold pending an appeal filed by the government over one count that was dismissed by the U.S. District Court judge","source":"https://www.documentcloud.org/documents/26185384-usa-v-blandon-saavedra-11591914-adf1-4348-832e-7227c44a9f1d/"},
    {"id":3,"date":"2025-08-24","defendant":"Steven Rivera","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault of a federal officer, damage to government property","chargeType":"felony","description":"A protester allegedly threw a beer can near federal agents. While the agents arrested him, the defendant allegedly shoved and punched them.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Accepted plea deal for a misdemeanor count; sentencing scheduled for June 10, 2026","source":"https://www.documentcloud.org/documents/26185385-usa-v-parra-eb582bc9-8347-4794-a651-57b0484777ae/"},
    {"id":4,"date":"2025-08-24","defendant":"Hector Manuel Rodriguez","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault of a federal officer, damage to government property","chargeType":"felony","description":"A protester allegedly threw a beer can near federal agents. While the agents arrested him, the defendant allegedly shoved and punched them.","outcome":"Dismissed","plea":"not guilty","court":"Central District of California","details":"Motion to dismiss granted on March 20, 2026","source":"https://www.documentcloud.org/documents/26185385-usa-v-parra-eb582bc9-8347-4794-a651-57b0484777ae/"},
    {"id":5,"date":"2025-08-24","defendant":"Juan Antonio Parra","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Defendant allegedly punched and kicked a van that was trying to pull into the Downtown Los Angeles federal building.","outcome":"Dismissed","plea":"n/a","court":"Central District of California","details":"Dismissed on Sept. 10, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.988827/gov.uscourts.cacd.988827.1.0.pdf"},
    {"id":6,"date":"2025-08-29","defendant":"Oscar Magana Reyes","location":"700 block of West Rialto Avenue, San Bernardino, California","address":"n/a","charge":"Assaulting, resisting or impeding certain officers or employees involving physical contact","chargeType":"felony","description":"CBP and ICE were conducting an immigration enforcement operation in San Bernardino when they saw a bicyclist who \"resembled the target\" of the operation, but wasn't, according to court documents. Even though it was the wrong person, agents tried to arrest the bicyclist, who allegedy bit an agent and stole an agent's taser and shocked them with it.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Accepted plea deal for a felony count; sentenced to time served","source":"https://www.documentcloud.org/documents/26185391-usa-v-reyes-2e1c6477-1625-4806-a97e-9c33025e82b9/"},
    {"id":7,"date":"2025-08-17","defendant":"Anthoney Edward Rosales","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"felony","description":"Defendant allegedly spit on a federal agent's leg during a protest.","outcome":"Pending","plea":"n/a","court":"Central District of California","details":"Trial date not listed on PACER","source":"https://www.documentcloud.org/documents/26185392-usa-v-rosales-1070b985-b779-4592-978d-6f6f49509074/"},
    {"id":8,"date":"2025-06-07","defendant":"Russell Gomez Dzul","location":"Los Angeles","address":"n/a","charge":"Assaulting, resisting or impeding officers","chargeType":"misdemeanor","description":"Border Patrol was conducting a roving patrol when they thought a man riding his bicycle looked \"startled and nervous.\" The bicyclist allegedly tried to escape when agents approached him and resisted their attempts to handcuff him.","outcome":"Not guilty","plea":"not guilty","court":"Central District of California","details":"Acquitted at trial on Jan. 14, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.974610/gov.uscourts.cacd.974610.1.0.pdf"},
    {"id":9,"date":"2025-06-12","defendant":"Javier Ramirez","location":"LA City Junk Cars in Montebello, California","address":"n/a","charge":"Assaulting, resisting or impeding officers","chargeType":"n/a","description":"Defendant, who was a U.S. citizen, was accused of resisting Border Patrol when they approached him at the auto yard where he worked.","outcome":"Dismissed","plea":"n/a","court":"Central District of California","details":"Complaint dismissed without prejudice","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.974696/gov.uscourts.cacd.974696.1.0.pdf"},
    {"id":10,"date":"2025-06-09","defendant":"Rene Luna","location":"Ronald Reagan Federal Building, Santa Ana","address":"n/a","charge":"Assault on federal officer","chargeType":"misdemeanor","description":"Defendant allegedly threw water bottles with \"unknown\" liquids inside during a protest.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Plea agreement for misdemeanor charge of obstruction of use of federal property, fined $100","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.976930/gov.uscourts.cacd.976930.45.0.pdf"},
    {"id":11,"date":"2025-06-07","defendant":"Emiliano Garduno Galvez","location":"6400 Alondra Blvd, Paramount, California","address":"n/a","charge":"Possession of an unregistered destructive device, civil disorder","chargeType":"felony","description":"Defendant allegedly threw a Molotov cocktail at federal agents during a protest near Home Depot, where there were reports of an immigration raid.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Pleaded guilty on Oct. 1, 2025; sentenced to 48 months in prison","source":"https://www.documentcloud.org/documents/26876330-45adccef-eeea-4814-bd7f-f667a5801629/"},
    {"id":12,"date":"2025-06-07","defendant":"Christian Damian Cerna Camacho","location":"6321 Alondra Blvd., Paramount, California","address":"n/a","charge":"Assault on federal officer","chargeType":"felony","description":"Defendant allegedly punched a Border Patrol agent during a protest.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Plea deal for misdemeanor charge. Sentencing scheduled for March 27, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.977318/gov.uscourts.cacd.977318.69.0.pdf"},
    {"id":13,"date":"2025-06-06","defendant":"David Jose Huerta","location":"2415 E. 15th St., Los Angeles","address":"n/a","charge":"Conspiracy to impede an officer","chargeType":"n/a","description":"Defendant allegedly obstructed the path to a gated driveway that federal vehicles were using during a protest.","outcome":"Pending","plea":"n/a","court":"Central District of California","details":"Facing a misdemeanor charge of obstruction, resistance or opposition of a federal officer. Hearing scheduled for May 18, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.991908/gov.uscourts.cacd.991908.29.0.pdf"},
    {"id":14,"date":"2025-06-07","defendant":"Gisselle Medina","location":"6300 block of Alondra Boulevard, Paramount, California","address":"n/a","charge":"Accessory after the fact","chargeType":"misdemeanor","description":"Defendant allegedly assisted other individuals who were accused of assaulting and impeding federal agents during a protest.","outcome":"Dismissed","plea":"n/a","court":"Central District of California","details":"Dismissed with prejudice on Feb. 17, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.977691/gov.uscourts.cacd.977691.15.0.pdf"},
    {"id":15,"date":"2025-06-07","defendant":"Elpidio Reyna","location":"6400 block of Alondra Boulevard, Paramount, California","address":"n/a","charge":"Assault on federal officer by deadly or dangerous weapon resulting in bodily injury","chargeType":"felony","description":"Defendant allegedly threw rocks and other debris at federal agents during a protest.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Plea agreement reached; sentencing scheduled for Aug. 7, 2026","source":"https://www.documentcloud.org/documents/25984206-5124e139-4676-47b5-820b-3cfaf73c5865/"},
    {"id":16,"date":"2025-06-13","defendant":"Geronimo Reyna","location":"n/a","address":"n/a","charge":"Concealing person from arrest","chargeType":"n/a","description":"Defendant allegedly transported his brother, who was accused of assaulting a federal officer, into Mexico by car in an attempt to evade arrest.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for Aug. 11, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.981713/gov.uscourts.cacd.981713.1.0.pdf"},
    {"id":17,"date":"2025-06-07","defendant":"Jacob Daniel Terrazas","location":"6321 Alondra Blvd., Paramount, California","address":"n/a","charge":"Simple assault on federal officer, assault of a federal employee using a deadly and dangerous weapon resulting in bodily injury","chargeType":"felony","description":"Defendant was allegedly throwing rocks and pieces of cinderblock at Border Patrol agents during a protest.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Pleaded guilty on Jan. 20, 2026; sentencing scheduled for April 6, 2026","source":"https://www.documentcloud.org/documents/25984212-0a6e45ac-e2ca-4448-b93d-ab0bb9791cb4/"},
    {"id":18,"date":"2025-07-25","defendant":"Maria De Jesus Garcia","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault on a federal officer or employee resulting in bodily injury","chargeType":"felony","description":"Defendant allegedly threw something at a CBP agent and bit the agent.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Accepted plea deal for misdemeanor count; sentencing scheduled for June 10, 2026","source":"https://www.documentcloud.org/documents/26079415-0832ee92-c689-41a9-b714-238b9c18e517/"},
    {"id":19,"date":"2025-07-23","defendant":"Fernando Flores","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault of a federal officer","chargeType":"felony","description":"Defendant allegedly shoved a Bureau of Prisons agent and grabbed her backpack.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Pleaded guilty; sentencing scheduled for May 13","source":"https://www.documentcloud.org/documents/26079702-46dc279f-2357-42c7-99e4-7bffb1baabb8/"},
    {"id":20,"date":"2025-07-14","defendant":"Alfonso Saldana-Solorio","location":"8000 block of Glencrest Drive, Sun Valley, California","address":"n/a","charge":"Assault on a federal officer or employee resulting in bodily injury","chargeType":"felony","description":"Defendant \"appeared to attempt to stike the officers\" who were trying to arrest him for removal proceedings. Defendant also allegedly kicked an agent.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for Aug. 4, 2026","source":"https://www.documentcloud.org/documents/26079546-3058be93-6b1e-4f50-a2a9-ee2aea6c882e/"},
    {"id":21,"date":"2025-06-07","defendant":"Mario Albert Castillo-Ortega","location":"1144 Circle City, Apt. 10, Corona, California","address":"n/a","charge":"Assault on a federal officer with a deadly and dangerous weapon","chargeType":"felony","description":"Defendant allegedly swerved his car into a government car when agents tried to arrest him for removal proceedings.","outcome":"Dismissed","plea":"n/a","court":"Central District of California","details":"Dismissed without prejudice upon motion of the government in November 2025","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.983087/gov.uscourts.cacd.983087.23.0.pdf"},
    {"id":22,"date":"2025-06-08","defendant":"Wrackkie Quiogue","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Possession of an unregistered destructive device","chargeType":"felony","description":"Defendant allegedly tried to set off a Molotov cocktail before federal agents stopped and arrested him.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Pleaded guilty on Nov. 19, 2025; sentencing was scheduled for May 6, 2026, but details were not available on PACER","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.975360/gov.uscourts.cacd.975360.1.0_2.pdf"},
    {"id":23,"date":"2025-07-02","defendant":"Jeane Wong","location":"San Diego County","address":"n/a","charge":"Assaulting, resisting or impeding federal officers","chargeType":"felony","description":"Defendant allegedly slapped a federal agent during an immigration enforcement operation in San Diego's Linda Vista neighborhood.","outcome":"Pending","plea":"not guilty","court":"Southern District of California","details":"Accepted a plea deal for a misdemeanor count; sentenced to 45 days of supervised probation","source":"https://storage.courtlistener.com/recap/gov.uscourts.casd.821025/gov.uscourts.casd.821025.1.0.pdf"},
    {"id":24,"date":"2025-07-02","defendant":"Raul Kuilon","location":"San Diego County","address":"n/a","charge":"Assaulting, resisting or impeding federal officers","chargeType":"felony","description":"Defendant allegedly crossed a police line and brought his arm down forcefully onto the forearm of a federal agent when agents tried to secure the perimeter.","outcome":"Dismissed","plea":"not guilty","court":"Southern District of California","details":"Government prosecutors filed a motion to dismiss the case without prejudice","source":"https://storage.courtlistener.com/recap/gov.uscourts.casd.821019/gov.uscourts.casd.821019.1.0.pdf"},
    {"id":25,"date":"2025-07-02","defendant":"Denis Anderson Chicoj-Yacon","location":"San Diego County","address":"n/a","charge":"Assaulting, resisting or impeding federal officers","chargeType":"felony","description":"HSI and CBP located a Guatemalan national for removal proceedings. He was in his car and refused to exit. After agents started trying to break into the car, he tried driving away and nearly struck agents who were standing close by.","outcome":"Dismissed","plea":"not guilty","court":"Southern District of California","details":"Case dismissed, but defendant is in ICE custody as of Oct. 12, 2025","source":"https://storage.courtlistener.com/recap/gov.uscourts.casd.821013/gov.uscourts.casd.821013.1.0.pdf"},
    {"id":26,"date":"2025-10-30","defendant":"Carlos Jimenez","location":"Ontario, California","address":"n/a","charge":"Assault on a federal officer","chargeType":"n/a","description":"Defendant was shot in the back of his shoulder when he stopped in his car near federal agents as they conducted a vehicle stop.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for June 22, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.993820/gov.uscourts.cacd.993820.1.0.pdf"},
    {"id":27,"date":"2025-11-06","defendant":"Robert Chavez Cortez","location":"800 N. Brookhurst St., Anaheim, California","address":"n/a","charge":"Assaulting, resisting or impeding a federal officer involving physical contact","chargeType":"n/a","description":"Defendant allegedly spit on a Border Patrol agent.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Accepted plea deal to be convicted for simple assault, sentenced to time served","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.994827/gov.uscourts.cacd.994827.1.0.pdf"},
    {"id":28,"date":"2025-11-04","defendant":"Christopher Chitwood","location":"650 Capitol Mall, Sacramento","address":"n/a","charge":"Assault on a federal officer","chargeType":"n/a","description":"Defendant allegedly assaulted a federal agent who was arresting someone else for trespassing on federal property.","outcome":"Pending","plea":"n/a","court":"Eastern District of California","details":"Status conference scheduled for June 22, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.caed.474537/gov.uscourts.caed.474537.1.0.pdf"},
    {"id":29,"date":"2025-06-11","defendant":"Esteban Armenta Arias","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Defendant allegedly picked up a water bottle and threw it at a federal agent during a protest at the federal building in Downtown L.A.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for Aug. 25, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.976593/gov.uscourts.cacd.976593.1.0.pdf"},
    {"id":30,"date":"2025-07-25","defendant":"Alexandria Demetrius Augustine","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"A federal agent tore up the defendant's umbrella, and the defendant allegedly threw the metal frame of the umbrella at the agent.","outcome":"Dismissed","plea":"not guilty","court":"Central District of California","details":"As of April 2026, pending charge of causing a disturbance","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.983602/gov.uscourts.cacd.983602.1.0.pdf"},
    {"id":31,"date":"2025-08-02","defendant":"Ashleigh Brown","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Defendant allegedly hit a federal agent \"in his left side with her right arm.\"","outcome":"Dismissed","plea":"not guilty","court":"Central District of California","details":"Government filed a motion to dismiss the charges","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.983586/gov.uscourts.cacd.983586.1.0.pdf"},
    {"id":32,"date":"2025-08-02","defendant":"Jonathon Redondo-Rosales","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"misdemeanor","description":"Defendant allegedly jumped on the hood of a government vehicle, then \"struck an officer in the face with his left hand\" to avoid arrest.","outcome":"Dismissed","plea":"n/a","court":"Central District of California","details":"Dismissed with prejudice on Feb. 6, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.983586/gov.uscourts.cacd.983586.1.0.pdf"},
    {"id":33,"date":"2025-06-08","defendant":"Kade Wilde Byrand","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Defendant was accused of pushing a Bureau of Prisons agent.","outcome":"Guilty","plea":"guilty","court":"Central District of California","details":"Pleaded guilty on Sept. 17, 2025; sentenced to time served (four days in prison), one year supervised release and fined $1,000","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.977308/gov.uscourts.cacd.977308.1.0_1.pdf"},
    {"id":34,"date":"2025-06-08","defendant":"Elmore Sylvester Cage","location":"Los Angeles","address":"n/a","charge":"Obstructing, impeding or interfering with law enforcement","chargeType":"n/a","description":"Defendant allegedly obstructed, impeded and interfered with LAPD.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for Sept. 28, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.995250/gov.uscourts.cacd.995250.71.0.pdf"},
    {"id":35,"date":"2025-06-06","defendant":"Yovany Macario Canil","location":"927 Stanford Ave., Los Angeles, California","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Defendant allegedly pepper-sprayed FBI SWAT team members who were executing a search warrant at a warehouse.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for Aug. 3, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.995909/gov.uscourts.cacd.995909.1.0.pdf"},
    {"id":36,"date":"2025-07-10","defendant":"Jonathan Caravello","location":"Glasshouse Farms, 645 Laguna Rd., Camarillo, California","address":"n/a","charge":"Assault on federal officer","chargeType":"felony","description":"Defendant allegedly threw a tear gas cannister back at federal agents while they executed a search warrant.","outcome":"Not guilty","plea":"not guilty","court":"Central District of California","details":"Found not guilty in an April 2026 jury trial","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.985175/gov.uscourts.cacd.985175.1.0.pdf"},
    {"id":37,"date":"2025-08-25","defendant":"Katherine Carreno","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Defendant allegedly used a \"slapping/chopping\" motion on an agent two times.","outcome":"Not guilty","plea":"not guilty","court":"Central District of California","details":"Found not guilty after jury trial","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.988835/gov.uscourts.cacd.988835.1.0.pdf"},
    {"id":38,"date":"2025-07-10","defendant":"Isai Carrillo","location":"Glasshouse Farms, 645 Laguna Rd., Camarillo, California","address":"n/a","charge":"Conspiracy to impede an officer, assaulting an officer with a deadly weapon","chargeType":"n/a","description":"Defendant allegedly threw rocks at government vehicles while they were trying to reach Glasshouse Farms.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for June 22, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.996095/gov.uscourts.cacd.996095.44.0.pdf"},
    {"id":39,"date":"2025-06-20","defendant":"Jose Cervantes Licea","location":"Jack's Car Wash & Detailing, 7030 Atlantic Ave, Bell, California","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Defendant charged into a Border Patrol agent, momentarily freeing an undocumented immigrant from apprehension.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Pleaded guilty on Aug. 29, 2025; sentenced to one year of probation","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.979897/gov.uscourts.cacd.979897.1.0.pdf"},
    {"id":40,"date":"2025-08-15","defendant":"Mario Chacon","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Defendant allegedly threw a water bottle that hit a federal agent in the head.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Pleaded guilty on Oct. 22, 2025, and sentenced Dec. 3 to time served (109 days in prison).","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.983338/gov.uscourts.cacd.983338.1.0.pdf"},
    {"id":41,"date":"2025-06-28","defendant":"Jose Francisco Cirenio-Marcos","location":"San Bernardino County West Valley Detention Center","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Defendant allegedly hid in a bathroom when ICE approached him and then resisted arrest when they tried to handcuff him.","outcome":"Dismissed","plea":"not guilty","court":"Central District of California","details":"Dismissed; defendant was deported","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.979844/gov.uscourts.cacd.979844.1.0.pdf"},
    {"id":42,"date":"2025-09-14","defendant":"Jose Cruz-Severiano","location":"Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Defendant allegedly \"made physical contact\" with a federal agent and caused an injury.","outcome":"Dismissed","plea":"not guilty","court":"Central District of California","details":"Dismissed on Nov. 12, 2025","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.991779/gov.uscourts.cacd.991779.12.0.pdf"},
    {"id":43,"date":"2025-07-08","defendant":"Danielle Nadine Davila","location":"SCA Health Ontario Advanced Surgery Center","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Defendant was one of two staffers at the surgical center who allegedly interfered with law enforcement as they were trying to apprehend an immigrant.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for June 22, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.984508/gov.uscourts.cacd.984508.31.0.pdf"},
    {"id":44,"date":"2025-07-08","defendant":"Jose de Jesus Ortega","location":"SCA Health Ontario Advanced Surgery Center","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Defendant was one of two staffers at the surgical center who allegedly interfered with law enforcement as they were trying to apprehend an immigrant.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for June 22, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.984508/gov.uscourts.cacd.984508.31.0.pdf"},
    {"id":45,"date":"2025-06-09","defendant":"Danny Duran","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"felony","description":"Defendant was allegedly driving a car by the federal building in Downtown L.A. when another defendant in the passenger seat fired paintballs at a Federal Protective Service officer.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for July 28, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.979442/gov.uscourts.cacd.979442.19.0.pdf"},
    {"id":46,"date":"2025-07-17","defendant":"Erin Escobar","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"felony","description":"Defendant was allegedly writing on federal property with a marker and after being arrested, spit on a Federal Protective Services officer.","outcome":"Dismissed","plea":"not guilty","court":"Central District of California","details":"Dismissed with prejudice.","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.983289/gov.uscourts.cacd.983289.1.0.pdf"},
    {"id":47,"date":"2025-07-17","defendant":"Nick Gutierrez","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"felony","description":"Defendant allegedly grabbed the bulletproof vest of a federal officer and began shaking him.","outcome":"Dismissed","plea":"not guilty","court":"Central District of California","details":"Dismissed with prejudice.","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.983289/gov.uscourts.cacd.983289.1.0.pdf"},
    {"id":48,"date":"2025-07-12","defendant":"Hector Galeano-Galindo","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Allegedly struck the arm of a Federal Protective Services agent who was trying to clear a path for an ICE van to enter the federal building driveway.","outcome":"Guilty","plea":"n/a","court":"Central District of California","details":"Pleaded guilty on Sept. 17, 2025, and sentenced to time served; fined $100","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.982645/gov.uscourts.cacd.982645.1.0.pdf"},
    {"id":49,"date":"2025-06-09","defendant":"Christian Andres Garcia","location":"34 Civic Center Plaza, Santa Ana, California","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Defendant allegedly threw objects at federal agents and a vehicle during a protest.","outcome":"Dismissed","plea":"not guilty","court":"Central District of California","details":"Dismissed on Jan. 7, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.977442/gov.uscourts.cacd.977442.1.0.pdf"},
    {"id":50,"date":"2025-08-25","defendant":"Hector Leiva Garcia","location":"Marina Del Ray","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Defendant was accused of kicking Border Patrol agents who were trying to check his immigration status, but he denied it.","outcome":"Dismissed","plea":"n/a","court":"Central District of California","details":"Dismissed on Sept. 9, 2025","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.984657/gov.uscourts.cacd.984657.1.0.pdf"},
    {"id":51,"date":"2025-07-21","defendant":"Carlos Gutierrez-Cardenas","location":"658 W. Holt Blvd, Suite A, Ontario, California","address":"n/a","charge":"Assaulting, resisting or impeding officers","chargeType":"n/a","description":"Defendant allegedly threw hot coffee on an ICE agent who was trying to arrest him for deportation proceedings.","outcome":"Dismissed","plea":"n/a","court":"Central District of California","details":"Dismissed on Aug. 22, 2025","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.980478/gov.uscourts.cacd.980478.1.0.pdf"},
    {"id":52,"date":"2025-06-12","defendant":"Thomas Guzman","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"misdemeanor","description":"Defendant threw a rock at a CBP officer at the federal building in Downtown Los Angeles.","outcome":"Guilty","plea":"guilty","court":"Central District of California","details":"Pleaded guilty July 17, 2025; sentenced to one year of probation","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.978055/gov.uscourts.cacd.978055.1.0.pdf"},
    {"id":53,"date":"2025-07-26","defendant":"Alireza Hamedani","location":"Rancho Santa Margarita, California","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Defendant allegedly drove his car into an HSI agent, who suffered a sprained elbow, while trying to arrest the defendant for deportation.","outcome":"Dismissed","plea":"n/a","court":"Central District of California","details":"Dismissed Sept. 23, 2025; in ICE custody","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.980977/gov.uscourts.cacd.980977.1.0.pdf"},
    {"id":54,"date":"2025-07-06","defendant":"Arturo Hermosillo","location":"San Pedro, California","address":"n/a","charge":"Conspiracy to impede an officer","chargeType":"n/a","description":"Defendant allegedly followed Border Patrol agents by car and blocked their vehicles.","outcome":"Dismissed","plea":"n/a","court":"Central District of California","details":"Dismissed on July 29, 2025","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.978018/gov.uscourts.cacd.978018.1.0.pdf"},
    {"id":55,"date":"2025-07-06","defendant":"Julian Pecora Carnedas","location":"San Pedro, California","address":"n/a","charge":"Conspiracy to impede an officer","chargeType":"n/a","description":"Defendant allegedly followed Border Patrol agents by car and blocked their vehicles.","outcome":"Dismissed","plea":"n/a","court":"Central District of California","details":"Dismissed on July 29, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.978018/gov.uscourts.cacd.978018.1.0.pdf"},
    {"id":56,"date":"2025-06-24","defendant":"Luis Dalhet Hipolito","location":"Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Defendant allegedly tried to block an ICE agent's vehicle and allegedly punched an agent in the face.","outcome":"Not guilty","plea":"not guilty","court":"Central District of California","details":"Found not guilty after jury trial from March 31 to April 1","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.979965/gov.uscourts.cacd.979965.1.0.pdf"},
    {"id":57,"date":"2025-06-24","defendant":"Andrea Guadalupe Velez","location":"Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Defendant allegedly stepped in front of an ICE agent who was chasing someone, then stuck the agent's head and chest by sticking her arms out.","outcome":"Dismissed","plea":"n/a","court":"Central District of California","details":"Dismissed on July 10, 2025","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.979965/gov.uscourts.cacd.979965.1.0.pdf"},
    {"id":58,"date":"2025-02-28","defendant":"Kiara Jaime-Flores","location":"Los Angeles","address":"n/a","charge":"Conspiracy to impede or injure officer","chargeType":"n/a","description":"Defendant and her boyfriend allegedly followed federal agents in their vehicle and blocked them, brake checked and otherwise impeded them.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Pleaded guilty on Dec. 1, 2025; sentenced to one year of probation","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.973089/gov.uscourts.cacd.973089.1.0_1.pdf"},
    {"id":59,"date":"2025-02-28","defendant":"Gustavo Torres","location":"Los Angeles","address":"n/a","charge":"Conspiracy to impede or injure officer","chargeType":"n/a","description":"Defendant and his girlfriend allegedly followed federal agents in their vehicle and blocked them, brake checked and otherwise impeded them.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Pleaded guilty on Dec. 1, 2025; sentenced to one year in prison","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.973089/gov.uscourts.cacd.973089.1.0_1.pdf"},
    {"id":60,"date":"2025-06-14","defendant":"Angus Johnson","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assaulting, resisting or impeding officers","chargeType":"misdemeanor","description":"Defendant spit on federal agents during the first No Kings protest in Downtown Los Angeles.","outcome":"Guilty","plea":"guilty","court":"Central District of California","details":"Pleaded guilty on Aug. 6, 2025; sentenced on Nov. 7 2025, to 14 days in prison and $100 fine","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.979765/gov.uscourts.cacd.979765.1.0.pdf"},
    {"id":61,"date":"2025-12-01","defendant":"Jose Francisco Jovel","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Attempted malicious damage of federal property","chargeType":"n/a","description":"Defendant allegedly threw two molotov cocktails at the Downtown Los Angeles federal building.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for Oct. 20, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.1000763/gov.uscourts.cacd.1000763.1.0.pdf"},
    {"id":62,"date":"2025-07-24","defendant":"Harold Lemus-Romero","location":"Santa Ana","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Defendant allegedly tried to escape DHS officers, including biting one agent, who tried to take him into custody in Santa Ana immigration court.","outcome":"Dismissed","plea":"n/a","court":"Central District of California","details":"Notice to dismiss filed on Nov. 17, 2025; defendant in ICE custody","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.980936/gov.uscourts.cacd.980936.1.0.pdf"},
    {"id":63,"date":"2025-08-08","defendant":"Francisco Javier Longoria","location":"n/a","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Defendant was arrested and charged with assaulting a federal officer in August 2025. The complaint with more details is not available on PACER.","outcome":"Dismissed","plea":"n/a","court":"Central District of California","details":"Dismissed on Sept. 17, 2025","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.985171/gov.uscourts.cacd.985171.9.0.pdf"},
    {"id":64,"date":"2025-08-08","defendant":"Isaias Lopez","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"felony","description":"Defendant allegedly hit an FPS agent in the nose with a camera as he jockeyed for position during a protest.","outcome":"Not guilty","plea":"n/a","court":"Central District of California","details":"Acquitted at trial, Jan. 29, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.986095/gov.uscourts.cacd.986095.1.0.pdf"},
    {"id":65,"date":"2025-06-09","defendant":"Edwin Osvaldo Manriquez","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"felony","description":"Defendant shot at federal agents with a paintball gun.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Accepted a plea deal to be convicted on a count of assault on a federal officer with a deadly or dangerous weapon.","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.979443/gov.uscourts.cacd.979443.1.0.pdf"},
    {"id":66,"date":"2025-06-17","defendant":"Adrian Andrew Martinez","location":"Pico Rivera","address":"n/a","charge":"Conspiracy to impede a federal officer","chargeType":"felony","description":"Defendant allegedly blocked a Border Patrol vehicle with his car and a trash can while agents were on a roving patrol.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for Aug. 17, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.985113/gov.uscourts.cacd.985113.1.0.pdf"},
    {"id":67,"date":"2025-08-25","defendant":"Cosmas Mitchell","location":"Home Depot, 12975 W. Jefferson, Los Angeles","address":"n/a","charge":"Depredation against federal property","chargeType":"n/a","description":"Threw a glass mason jar at federal agents during an immigration enforcement operation at a Home Depot.","outcome":"Guilty","plea":"guilty","court":"Central District of California","details":"Pleaded guilty on Dec. 12, 2025; sentencing scheduled for April 3, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.992005/gov.uscourts.cacd.992005.1.0.pdf"},
    {"id":68,"date":"2025-06-07","defendant":"Brayan Ramos-Brito","location":"6321 Alondra Blvd., Paramount, California","address":"n/a","charge":"Simple assault on federal officer","chargeType":"misdemeanor","description":"Defendant allegedly pushed a federal agent during a protest.","outcome":"Not guilty","plea":"not guilty","court":"Central District of California","details":"Found not guilty after a September 2025 trial","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.974128/gov.uscourts.cacd.974128.1.0.pdf"},
    {"id":69,"date":"2025-06-07","defendant":"Jose Manuel Mojica","location":"6321 Alondra Boulevard, Paramount, California","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Defendant allegedly pushed federal agents who were trying to arrest someone else during a protest.","outcome":"Dismissed","plea":"n/a","court":"Central District of California","details":"Dismissed on June 18, 2025","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.976960/gov.uscourts.cacd.976960.1.0.pdf"},
    {"id":70,"date":"2025-06-07","defendant":"Joceline Rodriguez","location":"6321 Alondra Blvd., Paramount, California","address":"n/a","charge":"Assault on federal officer","chargeType":"misdemeanor","description":"Defendant allegedly blocked federal vehicles trying to access an HSI building and then got into a physical confrontation with agents who tried to move her.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for Oct. 20, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.976960/gov.uscourts.cacd.976960.1.0.pdf"},
    {"id":71,"date":"2025-06-07","defendant":"Ashley Rodriguez","location":"6321 Alondra Boulevard, Paramount, California","address":"n/a","charge":"Assault on federal officer","chargeType":"misdemeanor","description":"Defendant allegedly blocked federal vehicles trying to access an HSI building and then got into a physical confrontation with agents who tried to move her.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for Oct. 20, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.976960/gov.uscourts.cacd.976960.1.0.pdf"},
    {"id":72,"date":"2025-06-27","defendant":"Matthew Jules Munoz","location":"Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"felony","description":"Defendant spit on a federal agent during an immigration enforcement operation in Downtown Los Angeles.","outcome":"Guilty","plea":"n/a","court":"Central District of California","details":"Pleaded guilty Dec. 9, 2025, to a misdemeanor charge, sentenced to three consecutive weekends of prison from Friday to Sunday starting Dec. 19.","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.985216/gov.uscourts.cacd.985216.1.0.pdf"},
    {"id":73,"date":"2025-06-28","defendant":"Juan Pablo Munoz-Hernandez","location":"9500 Etiwanda Ave, Rancho Cucamonga, California","address":"n/a","charge":"Assault on federal officer","chargeType":"felony","description":"Defendant struck a federal agent multiple times during a confrontation at the San Bernardino County Sheriff's Department West Valley Detention Center.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Pleaded guilty on Oct. 9, sentenced on Dec. 19 to time served","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.979178/gov.uscourts.cacd.979178.1.0.pdf"},
    {"id":74,"date":"2025-08-15","defendant":"Bobby Nunez","location":"Downtown Los Angeles","address":"n/a","charge":"Theft of government property in excess of $1,000","chargeType":"felony","description":"Defendant towed an ICE vehicle away during an immigration raid.","outcome":"Not guilty","plea":"not guilty","court":"Central District of California","details":"Acquitted on Dec. 19, 2025 after a jury trial.","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.988701/gov.uscourts.cacd.988701.1.0.pdf"},
    {"id":75,"date":"2025-06-09","defendant":"Alejandro Orellana","location":"Los Angeles","address":"n/a","charge":"Aiding and abetting","chargeType":"felony","description":"Defendant was handing out face shields to protesters to help protect them from nonlethals fired by federal agents.","outcome":"Dismissed","plea":"not guilty","court":"Central District of California","details":"Dismissed on July 30, 2025","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.978239/gov.uscourts.cacd.978239.1.0.pdf"},
    {"id":76,"date":"2025-07-19","defendant":"Margaret Sarah Ortiz","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"misdemeanor","description":"Defendant allegedly waved a flag, and the flag made contact with a federal officer's face.","outcome":"Dismissed","plea":"not guilty","court":"Central District of California","details":"Dismissed on Sept. 5, 2025","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.982647/gov.uscourts.cacd.982647.1.0.pdf"},
    {"id":77,"date":"2025-10-21","defendant":"Carlitos Ricardo Parias","location":"400 block of 20th Street, Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"felony","description":"Defendant allegedly maneuvered his car forward and backward into the cars of federal agents who tried to box him in during an attempted arrest. Agents shot the defendant.","outcome":"Dismissed","plea":"not guilty","court":"Central District of California","details":"Dismissed on Dec. 27, 2025, but government has appealed. Defendant is in ICE custody.","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.995241/gov.uscourts.cacd.995241.1.0.pdf"},
    {"id":78,"date":"2025-10-29","defendant":"Jesus Posadas-Espinoza","location":"402 N. A St., Oxnard, California","address":"n/a","charge":"Depredation of government property","chargeType":"misdemeanor","description":"Defendant allegedly threw hard items at government vehicles while agents were carrying out a search warrant.","outcome":"Dismissed","plea":"not guilty","court":"Central District of California","details":"Dismissed without prejudice on April 17, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.996750/gov.uscourts.cacd.996750.1.0.pdf"},
    {"id":79,"date":"2025-06-10","defendant":"Omar Pulido Bastida","location":"Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Defendant allegedly spit on an ICE agent who came to arrest him.","outcome":"Dismissed","plea":"n/a","court":"Central District of California","details":"Case for assault on an agent was dismissed, but defendant was convicted in a separate case for being in the U.S. illegally","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.975595/gov.uscourts.cacd.975595.1.0.pdf"},
    {"id":80,"date":"2025-08-15","defendant":"Avery Quinn Scopes Craft","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Damage to government property","chargeType":"n/a","description":"Defendant allegedly struck a federal van leaving the detention center with a flashlight or similarly sized item.","outcome":"Dismissed","plea":"n/a","court":"Central District of California","details":"Dismissed on Aug. 28, 2025","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.983338/gov.uscourts.cacd.983338.1.0.pdf"},
    {"id":81,"date":"2025-11-04","defendant":"Dennis Orlando Quinonez","location":"Home Depot, 2055 N. Figueroa St., Los Angeles","address":"n/a","charge":"Unlawful possession of firearm and ammo","chargeType":"n/a","description":"Defendant allegedly threw a rock at a Border Patrol vehicle while agents were trying to conduct an immigration operation by Home Depot. Agents found a gun in defendant's vehicle, which he was not supposed to have because of a previous domestic violence conviction.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for June 30, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.997744/gov.uscourts.cacd.997744.1.0.pdf"},
    {"id":82,"date":"2025-06-14","defendant":"Tony de Jesus Quintanilla","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Depredation of government property","chargeType":"misdemeanor","description":"Defendant allegedly spray painted something on the federal building in Downtown L.A.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Changed plea to guilty on Sept. 19, 2025, and sentenced to one year of probation and $1,850 in restitution","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.985077/gov.uscourts.cacd.985077.1.0.pdf"},
    {"id":83,"date":"2025-08-23","defendant":"Jessica Isabel Ramirez-Vasquez","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"felony","description":"Defendant allegedly kicked an agent and pulled an agent to the ground by his helmet strap.","outcome":"Dismissed","plea":"not guilty","court":"Central District of California","details":"Dismissed with prejudice on April 14, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.988580/gov.uscourts.cacd.988580.1.0.pdf"},
    {"id":84,"date":"2025-06-08","defendant":"Georgina Ravelero","location":"Downtown Los Angeles","address":"n/a","charge":"Obstructing, impeding or interfering with law enforcement","chargeType":"felony","description":"Allegedly drove on a motorcycle through a line of LAPD officers during a Downtown L.A. protest.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Pleaded guilty to a felony count on Jan. 5, 2026; sentencing scheduled for April 20, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.978179/gov.uscourts.cacd.978179.1.0.pdf"},
    {"id":85,"date":"2025-06-08","defendant":"Randy Paul Ruiz","location":"Downtown Los Angeles","address":"n/a","charge":"Obstructing, impeding or interfering with law enforcement","chargeType":"felony","description":"Allegedly drove on a motorcycle through a line of LAPD officers during a Downtown L.A. protest.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for June 9, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.978179/gov.uscourts.cacd.978179.1.0.pdf"},
    {"id":86,"date":"2025-08-28","defendant":"Cynthia Raygoza","location":"Baldwin Park","address":"n/a","charge":"Publicly disclosing the personal info of a federal agent","chargeType":"felony","description":"Allegedly followed an ICE agent from the Downtown L.A. federal building to his home, where a confrontation ensued.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Found guilty at trial, but motion for acquittal is pending","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.988766/gov.uscourts.cacd.988766.1.0.pdf"},
    {"id":87,"date":"2025-08-28","defendant":"Sandra Carmona Samane","location":"Baldwin Park","address":"n/a","charge":"Publicly disclosing the personal info of a federal agent","chargeType":"felony","description":"Allegedly followed an ICE agent from the Downtown L.A. federal building to his home, where a confrontation ensued.","outcome":"Not guilty","plea":"not guilty","court":"Central District of California","details":"Found not guilty after March 2026 jury trial","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.988766/gov.uscourts.cacd.988766.1.0.pdf"},
    {"id":88,"date":"2025-08-28","defendant":"Ashleigh Brown","location":"Baldwin Park","address":"n/a","charge":"Publicly disclosing the personal info of a federal agent","chargeType":"felony","description":"Allegedly followed an ICE agent from the Downtown L.A. federal building to his home, where a confrontation ensued.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Found guilty at trial, but motion for acquittal is pending","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.988766/gov.uscourts.cacd.988766.1.0.pdf"},
    {"id":89,"date":"2025-06-15","defendant":"Henry Rendon","location":"Bell Gardens, California","address":"n/a","charge":"Assaulting, resisting or impeding a federal officer","chargeType":"n/a","description":"Accused of striking a federal vehicle with his fist and then colliding into an agent's vehicle with his own car.","outcome":"Dismissed","plea":"n/a","court":"Central District of California","details":"Dismissed on July 17, 2025","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.976064/gov.uscourts.cacd.976064.1.0.pdf"},
    {"id":90,"date":"2025-06-10","defendant":"Virginia Reyes","location":"Ventura County","address":"n/a","charge":"Conspiracy to impede or injure a federal officer","chargeType":"felony","description":"Charged for her role in a rapid response network aimed at disrupting federal immigration enforcement.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for June 22, 2026","source":"https://www.documentcloud.org/documents/28117231-343f9bf0-f756-4e3f-a2cf-0df142ac2de8/"},
    {"id":91,"date":"2025-06-10","defendant":"Dominic Rios","location":"Downtown Los Angeles","address":"n/a","charge":"Aiming a laser pointer at an aircraft","chargeType":"felony","description":"Pointed a green laser pointer at an LAPD helicopter during a protest in Downtown Los Angeles.","outcome":"Guilty","plea":"n/a","court":"Central District of California","details":"Pleaded guilty on Aug. 28, 2025, to a felony count; sentenced Dec. 3, 2025, to one year probation and 50 hours community service","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.980417/gov.uscourts.cacd.980417.1.0.pdf"},
    {"id":92,"date":"2025-06-21","defendant":"Eric Anthony Rodriguez","location":"Los Angeles","address":"n/a","charge":"Possession of an unregistered destructive device","chargeType":"felony","description":"Threw a Molotov cocktail at the entrance of a Los Angeles hotel where federal agents were staying.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Accepted plea deal on Sept. 10, 2025; sentenced to five years in prison on March 18, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.982308/gov.uscourts.cacd.982308.1.0.pdf"},
    {"id":93,"date":"2025-06-08","defendant":"Alberto Sandoval-Alvarado","location":"n/a","address":"n/a","charge":"Harboring illegal aliens","chargeType":"misdemeanor","description":"Tried to evade Border Patrol by driving onto a gated commercial property with his cousin's husband, who was not authorized to be in the U.S.","outcome":"Guilty","plea":"n/a","court":"Central District of California","details":"Plea agreement filed April 30, 2026. Change of plea and sentencing hearing scheduled for June 25, 2026","source":"https://www.documentcloud.org/documents/28117368-522c1a01-1f84-4346-82ad-065e9a30e8a5/"},
    {"id":94,"date":"2025-07-03","defendant":"Gabriel Rodriguez","location":"Anaheim Car Wash, 400 N. State College Blvd., Anaheim, California","address":"n/a","charge":"Depredation of government property","chargeType":"misdemeanor","description":"Threw a piece of wood that shattered the windshield of a Border Patrol vehicle.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Pleaded guilty Sept. 12, 2025; sentenced Oct. 8, 2025 to eight months in prison, $325 restitution","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.982348/gov.uscourts.cacd.982348.1.0_2.pdf"},
    {"id":95,"date":"2026-01-09","defendant":"Kaden Rummler","location":"34 Civic Center Drive, Santa Ana, California","address":"n/a","charge":"Disorderly conduct","chargeType":"n/a","description":"Issued a citation for allegedly protesting on federal property that had been closed off to the public and for interfering with the arrest of another protester.","outcome":"Pending","plea":"n/a","court":"Central District of California","details":"Court appearance scheduled for May 27, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.1009226/gov.uscourts.cacd.1009226.1.0.pdf"},
    {"id":96,"date":"2026-01-09","defendant":"Katelyn Skye Seitz","location":"34 Civic Center Drive, Santa Ana, California","address":"n/a","charge":"Simple assault on federal officer","chargeType":"misdemeanor","description":"Threw an orange cone toward an FPS agent, then struck an agent in the shoulder and groin while detained.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Accepted a plea deal March 5, 2026, and sentenced to one year probation","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.1006986/gov.uscourts.cacd.1006986.1.0_2.pdf"},
    {"id":97,"date":"2025-06-20","defendant":"Jorge Sierra Hernandez","location":"Bell, California","address":"n/a","charge":"Injuring government property","chargeType":"n/a","description":"Accused of initiating a vehicle collision to prevent Border Patrol from making an arrest.","outcome":"Dismissed","plea":"n/a","court":"Central District of California","details":"Dismissed on July 17, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.977033/gov.uscourts.cacd.977033.1.0.pdf"},
    {"id":98,"date":"2025-09-07","defendant":"Ceasar Salvador Sigala","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"felony","description":"Allegedly jabbed an HSI agent during the attempted arrest of another individual, who allegedly escaped due to Sigala's intervention.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for Sept 15, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.989306/gov.uscourts.cacd.989306.1.0.pdf"},
    {"id":99,"date":"2026-07-05","defendant":"Robert Strong","location":"21218 Roscoe Boulevard, Canoga Park, California","address":"n/a","charge":"Assault on federal officer","chargeType":"felony","description":"Allegedly punched and kicked agents during an immigration enforcement operation, and hit an agent with a baton that one of the agents dropped.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for Nov. 10, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.980763/gov.uscourts.cacd.980763.1.0.pdf"},
    {"id":100,"date":"2025-09-25","defendant":"Jessica Elizabeth Trapp","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"felony","description":"Allegedly kicked a Federal Protective Service officer after attending a detention hearing at the federal building in Downtown L.A.","outcome":"Not guilty","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for April 21, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.991901/gov.uscourts.cacd.991901.1.0.pdf"},
    {"id":101,"date":"2025-07-04","defendant":"Noe Vacilio","location":"Crenshaw and West Century boulevards, Inglewood","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Defendant allegedly tried to flee Border Patrol agents during an immigration enforcement operation, and later punched an agent in the helmet three times while resisting arrest.","outcome":"Dismissed","plea":"n/a","court":"Central District of California","details":"Dismissed on Aug. 6, 2025","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.979812/gov.uscourts.cacd.979812.1.0.pdf"},
    {"id":102,"date":"2025-06-08","defendant":"Yachua Mauricio Flores","location":"Los Angeles","address":"n/a","charge":"Attempted malicious damage of a government vehicle","chargeType":"n/a","description":"One of nine defendants charged with trying to set fire to a California Highway Patrol vehicle or attempting to obstruct or impede law enforcement in the process.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Accepted plea deal to be convicted with a felony count of obstructing, impeding and interfering with law enforcement during a civil disorder.","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.987494/gov.uscourts.cacd.987494.106.0.pdf"},
    {"id":103,"date":"2025-06-08","defendant":"Stefano Deong Green","location":"Los Angeles","address":"n/a","charge":"Attempted malicious damage of a government vehicle","chargeType":"n/a","description":"One of nine defendants charged with trying to set fire to a California Highway Patrol vehicle or attempting to obstruct or impede law enforcement in the process.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for June 16, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.987494/gov.uscourts.cacd.987494.106.0.pdf"},
    {"id":104,"date":"2025-06-08","defendant":"Jesus Gonzalez Hernandez Jr.","location":"Los Angeles","address":"n/a","charge":"Attempted malicious damage of a government vehicle","chargeType":"n/a","description":"One of nine defendants charged with trying to set fire to a California Highway Patrol vehicle or attempting to obstruct or impede law enforcement in the process.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Accepted guilty plea for misdemeanor count of simple assault on a person assisting a federal officer.","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.987494/gov.uscourts.cacd.987494.106.0.pdf"},
    {"id":105,"date":"2025-06-08","defendant":"Adam Charles Palermo","location":"Los Angeles","address":"n/a","charge":"Attempted malicious damage of a government vehicle","chargeType":"n/a","description":"Defendant allegedly threw a \"flaming object\" at a California Highway Patrol vehicle during a protest.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Accepted plea deal to be convicted with a felony count of assaulting, resisting and impeding persons assisting federal officers.","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.987495/gov.uscourts.cacd.987495.16.0.pdf"},
    {"id":106,"date":"2025-06-08","defendant":"Balto Montion","location":"Los Angeles","address":"n/a","charge":"Attempted malicious damage of a government vehicle","chargeType":"n/a","description":"One of nine defendants charged with trying to set fire to a California Highway Patrol vehicle or attempting to obstruct or impede law enforcement in the process.","outcome":"Guilty","plea":"n/a","court":"Central District of California","details":"Accepted plea deal to be convicted on a felony count of obstructing, impeding and interfering with law enforcement.","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.987494/gov.uscourts.cacd.987494.106.0.pdf"},
    {"id":107,"date":"2025-06-08","defendant":"Hector Daniel Ramos","location":"Los Angeles","address":"n/a","charge":"Attempted malicious damage of a government vehicle","chargeType":"n/a","description":"One of nine defendants charged with trying to set fire to a California Highway Patrol vehicle or attempting to obstruct or impede law enforcement in the process.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for June 23, 2026","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.987494/gov.uscourts.cacd.987494.106.0.pdf"},
    {"id":108,"date":"2025-06-08","defendant":"Junior Roldan","location":"Los Angeles","address":"n/a","charge":"Attempted malicious damage of a government vehicle","chargeType":"n/a","description":"One of nine defendants charged with trying to set fire to a California Highway Patrol vehicle or attempting to obstruct or impede law enforcement in the process.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Accepted plea deal to be convicted on a misdemeanor count of simple assault on a person assisting a federal officer.","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.987494/gov.uscourts.cacd.987494.106.0.pdf"},
    {"id":109,"date":"2025-06-08","defendant":"Ismael Vega","location":"Los Angeles","address":"n/a","charge":"Attempted malicious damage of a government vehicle","chargeType":"n/a","description":"One of nine defendants charged with trying to set fire to a California Highway Patrol vehicle or attempting to obstruct or impede law enforcement in the process.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Accepted plea deal to be convicted on a count of obstructing, impeding and interfering with law enforcement during a civil disorder.","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.987494/gov.uscourts.cacd.987494.106.0.pdf"},
    {"id":110,"date":"2025-06-08","defendant":"Ronald Alexis Coreas","location":"Los Angeles","address":"n/a","charge":"Attempted malicious damage of a government vehicle","chargeType":"n/a","description":"One of nine defendants charged with trying to set fire to a California Highway Patrol vehicle or attempting to obstruct or impede law enforcement in the process.","outcome":"Guilty","plea":"not guilty","court":"Central District of California","details":"Accepting plea deal to be convicted on misdemeanor count of simple assault on a person assisting a federal officer.","source":"https://storage.courtlistener.com/recap/gov.uscourts.cacd.987494/gov.uscourts.cacd.987494.106.0.pdf"},
    {"id":111,"date":"2026-03-28","defendant":"Sherman Reid","location":"Roybal Federal Building, Downtown Los Angeles","address":"n/a","charge":"Assault on federal officer","chargeType":"n/a","description":"Allegedly picked up a tear gas canister and threw it back toward federal agents, striking one of them in the chest.","outcome":"Pending","plea":"not guilty","court":"Central District of California","details":"Trial scheduled for June 9, 2026","source":"https://www.documentcloud.org/documents/28078595-shermanreid-031147563980/"}
  ];

  const toggleCase = (id) => {
    const newExpanded = new Set(expandedCases);
    if (newExpanded.has(id)) {
      newExpanded.delete(id);
    } else {
      newExpanded.add(id);
    }
    setExpandedCases(newExpanded);
  };

  const formatDate = (dateString) => {
    if (!dateString || dateString === 'n/a') return 'Date unknown';
    const [year, month, day] = dateString.split('-');
    const date = new Date(year, month - 1, day);
    return date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  };

  const getOutcomeColor = (outcome) => {
    const o = outcome.toLowerCase();
    if (o === 'guilty') return 'bg-red-100 text-red-800';
    if (o === 'pending') return 'bg-yellow-100 text-yellow-800';
    if (o === 'dismissed') return 'bg-green-100 text-green-800';
    if (o === 'not guilty') return 'bg-blue-100 text-blue-800';
    return 'bg-gray-100 text-gray-800';
  };

  const statusConfig = [
    { key: 'Pending',    label: 'Pending',    color: 'bg-yellow-400', text: 'text-yellow-900' },
    { key: 'Guilty',     label: 'Guilty',     color: 'bg-red-500',    text: 'text-white'      },
    { key: 'Dismissed',  label: 'Dismissed',  color: 'bg-green-500',  text: 'text-white'      },
    { key: 'Not guilty', label: 'Not Guilty', color: 'bg-blue-500',   text: 'text-white'      },
  ];

  const statusCounts = statusConfig.map(s => ({
    ...s,
    count: cases.filter(c => c.outcome.toLowerCase() === s.key.toLowerCase()).length,
  }));
  const total = cases.length;

  const filteredCases = selectedStatus === 'all'
    ? cases
    : cases.filter(c => c.outcome.toLowerCase() === selectedStatus.toLowerCase());

  const casesByDate = filteredCases.reduce((acc, c) => {
    const key = c.date && c.date !== 'n/a' ? c.date : 'n/a';
    if (!acc[key]) acc[key] = [];
    acc[key].push(c);
    return acc;
  }, {});

  const sortedDates = Object.keys(casesByDate).sort((a, b) => {
    if (a === 'n/a') return 1;
    if (b === 'n/a') return -1;
    return new Date(a) - new Date(b);
  });

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 p-4 md:p-8">
      <div className="max-w-7xl mx-auto">
        <div className="mb-8">
          <h1 className="text-3xl md:text-4xl font-bold text-slate-800 mb-2">
            A timeline of alleged assaults committed against federal agents in California since the immigration raids started
          </h1>
          <p className="text-slate-600 mb-1">Data compiled by Luke Harold. Coding by Claude.ai.</p>
          <p className="text-slate-500 text-sm mb-4">Last updated: May 13, 2026</p>

          {/* About */}
          <div className="p-5 bg-white rounded-lg shadow-md border border-slate-200 mb-4">
            <h3 className="font-semibold text-slate-800 mb-2">About this visualization</h3>
            <p className="text-slate-600 text-sm">
              This timeline displays {cases.length} federal court cases involving charges of assaulting or impeding federal officers in California, grouped by incident date. Cases were located using PACER and by contacting the courts directly; it's possible there are others not listed here. Use PACER or CourtListener for the most up-to-date information about any given case. Use the filter below to view cases by status. Click "View Details" on any card to see the court, plea, and links to source documents.
            </p>
          </div>

          {/* Merged clickable status bar */}
          <div className="bg-white rounded-lg shadow-md p-4 border border-slate-200">
            <div className="flex items-center justify-between mb-3">
              <h2 className="text-sm font-semibold text-slate-600 uppercase tracking-wide">Case Status — click to filter</h2>
              {selectedStatus !== 'all' && (
                <button
                  onClick={() => setSelectedStatus('all')}
                  className="text-xs text-blue-600 hover:text-blue-800 font-medium underline"
                >
                  Show all
                </button>
              )}
            </div>
            <div className="flex rounded-lg overflow-hidden h-8 mb-3 cursor-pointer">
              {statusCounts.map(s => (
                <div
                  key={s.key}
                  onClick={() => setSelectedStatus(selectedStatus === s.key ? 'all' : s.key)}
                  className={`${s.color} flex items-center justify-center transition-all hover:opacity-80 ${
                    selectedStatus !== 'all' && selectedStatus !== s.key ? 'opacity-30' : ''
                  }`}
                  style={{ width: `${(s.count / total) * 100}%`, minWidth: s.count > 0 ? '2rem' : '0' }}
                  title={`Click to filter: ${s.label} (${s.count})`}
                >
                  {s.count > 0 && (
                    <span className={`text-xs font-bold ${s.text} whitespace-nowrap px-1`}>
                      {s.count}
                    </span>
                  )}
                </div>
              ))}
            </div>
            <div className="flex flex-wrap gap-3">
              {statusCounts.map(s => (
                <button
                  key={s.key}
                  onClick={() => setSelectedStatus(selectedStatus === s.key ? 'all' : s.key)}
                  className={`flex items-center gap-1.5 text-sm rounded-md px-2 py-1 transition-colors ${
                    selectedStatus === s.key
                      ? 'bg-slate-200 font-semibold text-slate-900'
                      : selectedStatus !== 'all'
                      ? 'text-slate-400 hover:text-slate-700'
                      : 'text-slate-700 hover:bg-slate-100'
                  }`}
                >
                  <span className={`inline-block w-3 h-3 rounded-sm ${s.color}`}></span>
                  <span>{s.label}: <strong>{s.count}</strong> ({Math.round((s.count / total) * 100)}%)</span>
                </button>
              ))}
            </div>
          </div>
        </div>

        {sortedDates.length === 0 ? (
          <div className="bg-white rounded-lg shadow-md p-8 text-center border border-slate-200">
            <p className="text-slate-600">No cases match the selected filter.</p>
          </div>
        ) : (
          <div className="space-y-12">
            {sortedDates.map((date) => (
              <div key={date}>
                <div className="flex items-center gap-3 mb-6">
                  <div className="bg-blue-600 text-white px-4 py-2 rounded-lg shadow-md flex items-center gap-2">
                    <Calendar className="w-5 h-5" />
                    <span className="font-semibold text-lg">{formatDate(date)}</span>
                  </div>
                  <div className="text-sm text-slate-600 font-medium">
                    {casesByDate[date].length} {casesByDate[date].length === 1 ? 'case' : 'cases'}
                  </div>
                  <div className="h-0.5 flex-grow bg-slate-300"></div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  {casesByDate[date].map((caseItem) => (
                    <div
                      key={caseItem.id}
                      className="bg-white rounded-lg shadow-md hover:shadow-xl transition-all border border-slate-200 overflow-hidden flex flex-col"
                    >
                      <div className="p-5 flex-grow">
                        <div className="flex items-start justify-between mb-3">
                          <div className="flex-grow pr-2">
                            <h3 className="text-base font-bold text-slate-800 leading-tight mb-1">
                              {caseItem.defendant}
                            </h3>
                            <p className="text-sm text-slate-600 leading-tight mb-1">
                              {caseItem.charge !== 'n/a' ? caseItem.charge : 'Charge not listed'}
                            </p>
                            {caseItem.chargeType && caseItem.chargeType !== 'n/a' && (
                              <span className="text-xs text-slate-500 font-medium">
                                {caseItem.chargeType}
                              </span>
                            )}
                          </div>
                          <span className={`px-2 py-1 rounded-full text-xs font-medium whitespace-nowrap ${getOutcomeColor(caseItem.outcome)}`}>
                            {caseItem.outcome}
                          </span>
                        </div>

                        <div className="space-y-2 text-sm text-slate-600 mb-4">
                          {caseItem.description !== 'n/a' && (
                            <div className="flex items-start gap-2">
                              <FileText className="w-4 h-4 flex-shrink-0 mt-0.5" />
                              <span className="text-sm leading-relaxed">{caseItem.description}</span>
                            </div>
                          )}
                          {caseItem.location !== 'n/a' && (
                            <div className="flex items-start gap-2">
                              <MapPin className="w-4 h-4 flex-shrink-0 mt-0.5" />
                              <span className="text-xs">{caseItem.location}</span>
                            </div>
                          )}
                        </div>

                        {expandedCases.has(caseItem.id) && (
                          <div className="mt-4 pt-4 border-t border-slate-200 space-y-3">
                            {caseItem.plea && caseItem.plea !== 'n/a' && (
                              <div>
                                <h4 className="font-semibold text-slate-700 mb-1 text-sm">Plea</h4>
                                <p className="text-slate-600 text-sm capitalize">{caseItem.plea}</p>
                              </div>
                            )}
                            {caseItem.court && caseItem.court !== 'n/a' && (
                              <div>
                                <h4 className="font-semibold text-slate-700 mb-1 text-sm flex items-center gap-1">
                                  <Scale className="w-4 h-4" />
                                  Court
                                </h4>
                                <p className="text-slate-600 text-sm">{caseItem.court}</p>
                              </div>
                            )}
                            {caseItem.details && caseItem.details !== 'n/a' && (
                              <div>
                                <h4 className="font-semibold text-slate-700 mb-1 text-sm">Case Details</h4>
                                <p className="text-slate-600 text-sm">{caseItem.details}</p>
                              </div>
                            )}
                            {caseItem.source && caseItem.source !== 'n/a' && (
                              <div>
                                <a
                                  href={caseItem.source}
                                  target="_blank"
                                  rel="noopener noreferrer"
                                  className="text-blue-600 hover:text-blue-800 text-sm flex items-center gap-1"
                                >
                                  <ExternalLink className="w-3 h-3" />
                                  View Court Documents
                                </a>
                              </div>
                            )}
                          </div>
                        )}
                      </div>

                      <button
                        onClick={() => toggleCase(caseItem.id)}
                        className="w-full bg-slate-50 hover:bg-slate-100 transition-colors py-2 px-5 flex items-center justify-center gap-2 text-slate-700 text-sm font-medium border-t border-slate-200"
                      >
                        {expandedCases.has(caseItem.id) ? (
                          <>
                            <span>Show Less</span>
                            <ChevronUp className="w-4 h-4" />
                          </>
                        ) : (
                          <>
                            <span>View Details</span>
                            <ChevronDown className="w-4 h-4" />
                          </>
                        )}
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        )}


      </div>
    </div>
  );
};

export default CourtCaseTimeline;